In [2]:
#importing all the necessary libraries and frameworks required
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn 
from sklearn import preprocessing
import cv2


In [3]:
#importing the dataset
data = pd.read_csv("C:/Users/Dell/Documents/temperature_data.csv")
data

Column1
0      28.82
1      28.96
2      28.43
3      28.08
4      27.17
..       ...
763    25.46
764    25.68
765    25.72
766    27.53
767    28.94

[768 rows x 1 columns]

In [4]:
# convert csv file into an array for a better processing

data1= np.array(data)
data1

array([[28.82],
       [28.96],
       [28.43],
       [28.08],
       [27.17],
       [26.88],
       [25.58],
       [25.54],
       [25.15],
       [25.33],
       [25.11],
       [24.99],
       [24.82],
       [25.64],
       [24.82],
       [24.91],
       [24.91],
       [25.44],
       [25.29],
       [25.26],
       [24.98],
       [25.7 ],
       [25.37],
       [26.1 ],
       [26.28],
       [26.88],
       [27.15],
       [27.59],
       [27.43],
       [27.67],
       [29.2 ],
       [29.15],
       [29.39],
       [27.97],
       [27.99],
       [27.86],
       [26.53],
       [25.73],
       [25.09],
       [25.32],
       [25.02],
       [24.88],
       [25.1 ],
       [24.85],
       [25.07],
       [24.99],
       [24.94],
       [24.83],
       [26.  ],
       [24.84],
       [25.3 ],
       [25.78],
       [25.86],
       [25.66],
       [25.47],
       [26.2 ],
       [26.66],
       [26.75],
       [27.47],
       [27.03],
       [27.79],
       [27.57],
       [

In [5]:
#Sample sensor data
sensor_data = [num for num in data1]
sensor_data

[array([0.2882]),
 array([0.2896]),
 array([0.2843]),
 array([0.2808]),
 array([0.2717]),
 array([0.2688]),
 array([0.2558]),
 array([0.2554]),
 array([0.2515]),
 array([0.2533]),
 array([0.2511]),
 array([0.2499]),
 array([0.2482]),
 array([0.2564]),
 array([0.2482]),
 array([0.2491]),
 array([0.2491]),
 array([0.2544]),
 array([0.2529]),
 array([0.2526]),
 array([0.2498]),
 array([0.257]),
 array([0.2537]),
 array([0.261]),
 array([0.2628]),
 array([0.2688]),
 array([0.2715]),
 array([0.2759]),
 array([0.2743]),
 array([0.2767]),
 array([0.292]),
 array([0.2915]),
 array([0.2939]),
 array([0.2797]),
 array([0.2799]),
 array([0.2786]),
 array([0.2653]),
 array([0.2573]),
 array([0.2509]),
 array([0.2532]),
 array([0.2502]),
 array([0.2488]),
 array([0.251]),
 array([0.2485]),
 array([0.2507]),
 array([0.2499]),
 array([0.2494]),
 array([0.2483]),
 array([0.26]),
 array([0.2484]),
 array([0.253]),
 array([0.2578]),
 array([0.2586]),
 array([0.2566]),
 array([0.2547]),
 array([0.262]),


In [6]:
#Reshaping the data into a 24x32 thermal image as required
thermal_image = np.array(sensor_data).reshape(24,32)
thermal_image

array([[0.2882, 0.2896, 0.2843, 0.2808, 0.2717, 0.2688, 0.2558, 0.2554,
        0.2515, 0.2533, 0.2511, 0.2499, 0.2482, 0.2564, 0.2482, 0.2491,
        0.2491, 0.2544, 0.2529, 0.2526, 0.2498, 0.257 , 0.2537, 0.261 ,
        0.2628, 0.2688, 0.2715, 0.2759, 0.2743, 0.2767, 0.292 , 0.2915],
       [0.2939, 0.2797, 0.2799, 0.2786, 0.2653, 0.2573, 0.2509, 0.2532,
        0.2502, 0.2488, 0.251 , 0.2485, 0.2507, 0.2499, 0.2494, 0.2483,
        0.26  , 0.2484, 0.253 , 0.2578, 0.2586, 0.2566, 0.2547, 0.262 ,
        0.2666, 0.2675, 0.2747, 0.2703, 0.2779, 0.2757, 0.2798, 0.2965],
       [0.2811, 0.2849, 0.2669, 0.2664, 0.2518, 0.2523, 0.2491, 0.2471,
        0.246 , 0.2506, 0.2443, 0.2481, 0.2481, 0.2448, 0.2503, 0.2496,
        0.2508, 0.2543, 0.2506, 0.2514, 0.2546, 0.2579, 0.2611, 0.2602,
        0.2652, 0.2713, 0.2738, 0.2797, 0.2685, 0.2814, 0.2933, 0.2904],
       [0.2811, 0.2728, 0.2653, 0.2613, 0.2555, 0.2432, 0.2461, 0.2452,
        0.2525, 0.2456, 0.247 , 0.247 , 0.2525, 0.2464, 0.248

In [7]:
#Upscale the image for better visibility
upscale_factor = 4
image = thermal_image.astype(np.float32)
thermal_image= cv2.resize(image, (32*upscale_factor, 24*upscale_factor))
thermal_image

array([[0.2882    , 0.2882    , 0.288375  , ..., 0.2915625 , 0.2915    ,
        0.2915    ],
       [0.2882    , 0.2882    , 0.288375  , ..., 0.2915625 , 0.2915    ,
        0.2915    ],
       [0.2889125 , 0.2889125 , 0.28884375, ..., 0.29191875, 0.292125  ,
        0.292125  ],
       ...,
       [0.26278752, 0.26278752, 0.2621922 , ..., 0.28684843, 0.2887    ,
        0.2887    ],
       [0.2632    , 0.2632    , 0.26255   , ..., 0.2876375 , 0.2894    ,
        0.2894    ],
       [0.2632    , 0.2632    , 0.26255   , ..., 0.2876375 , 0.2894    ,
        0.2894    ]], dtype=float32)

In [8]:
#Smoothening the image to reduce pixelation using Gaussian Blur filter
thermal_image = cv2.GaussianBlur(thermal_image,(0,0),5)
thermal_image

array([[0.2863263 , 0.2862441 , 0.28599972, ..., 0.2881062 , 0.28848958,
        0.28861943],
       [0.2862459 , 0.2861631 , 0.28591684, ..., 0.28807825, 0.2884608 ,
        0.28859043],
       [0.28600425, 0.28591958, 0.28566805, ..., 0.28799284, 0.288373  ,
        0.2885018 ],
       ...,
       [0.25691363, 0.2568373 , 0.25661162, ..., 0.2755989 , 0.27624562,
        0.27646574],
       [0.25715685, 0.257078  , 0.25684488, ..., 0.27571875, 0.27637127,
        0.27659348],
       [0.25723946, 0.2571597 , 0.25692406, ..., 0.27576044, 0.27641496,
        0.27663776]], dtype=float32)

In [23]:
#Find the clodest and hottest temperatures
min_temp = np.min(thermal_image)
def index(array, item): #index required to form the marks for the hottest and coldest temperatures
    for index, val in np.ndenumerate(array):
        if val == item:
            return index
min_idx_temp = (index(thermal_image, min_temp)) #index of minimum temperature
max_temp = np.max(thermal_image)
max_idx_temp = (index(thermal_image, max_temp))#index of maximum temperature
min_temp,max_temp,min_idx_temp,max_idx_temp

(0.24016464, 0.32009315, (60, 37), (43, 127))

In [26]:
#Mark the coldest and the hottest temperatures using a circle
coldest_colour = (255,0,0) #blue
hottest_colour = (0,0,255) #red
thermal_image_with_marks = thermal_image.copy()
cv2.circle(thermal_image_with_marks, min_idx_temp,20, coldest_colour,2) #marking for coldest temp
cv2.circle(thermal_image_with_marks, max_idx_temp,20, hottest_colour,2) #marking for hottest temp



array([[0.2863263 , 0.2862441 , 0.28599972, ..., 0.2881062 , 0.28848958,
        0.28861943],
       [0.2862459 , 0.2861631 , 0.28591684, ..., 0.28807825, 0.2884608 ,
        0.28859043],
       [0.28600425, 0.28591958, 0.28566805, ..., 0.28799284, 0.288373  ,
        0.2885018 ],
       ...,
       [0.25691363, 0.2568373 , 0.25661162, ..., 0.2755989 , 0.27624562,
        0.27646574],
       [0.25715685, 0.257078  , 0.25684488, ..., 0.27571875, 0.27637127,
        0.27659348],
       [0.25723946, 0.2571597 , 0.25692406, ..., 0.27576044, 0.27641496,
        0.27663776]], dtype=float32)

In [27]:
#Displaying the final image
cv2.imshow("Thermal Image", image)
cv2.waitKey(0) 
cv2.destroyAllWindows()
